export const groups = [
  {
    id: "anemones",
    parentId: "cnidarians",
    title: { en: "Anemones and ceriantharians", fr: "Anémones et cérianthaires" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47797, 47705],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/60993449/original.jpeg"],
  },
  {
    id: "angelfishes",
    parentId: "fishes",
    title: { en: "Angelfishes", fr: "Poissons-Anges" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47237],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/231970034/original.jpg"],
  },
  {
    id: "angiosperms",
    parentId: "flora",
    title: { en: "Angiosperms", fr: "Angiospermes" },
    subtitle: { en: "Flowering plants", fr: "Plantes à fleurs" },
    showSpecies: true,
    includesTaxa: [47125],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/97519807/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/918746/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/829832/original.JPG",
    ],
  },
  {
    id: "anguilliformes",
    parentId: "fishes",
    title: { en: "Eels, congers, morays", fr: "Anguilles, congres, murènes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47314],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/60018095/original.jpg"],
  },
  {
    id: "annelids",
    parentId: "fauna",
    title: { en: "Annelids", fr: "Annelides" },
    subtitle: { en: "Ringed worms", fr: "Ver annelés" },
    showSpecies: true,
    includesTaxa: [47491],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/29937090/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/12707460/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/665005/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/6573153/original.jpg",
    ],
  },
  {
    id: "ascidians",
    parentId: "fauna",
    title: { en: "Ascidians", fr: "Ascidies" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [130868],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/106143828/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/656071/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/776565/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/613131/original.jpg",
    ],
  },
  {
    id: "astacidea",
    parentId: "crustaceans",
    title: { en: "Lobsters, crayfish, prawns", fr: "Homards, écrevisses, langoustes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [311310],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/70180984/original.jpg"],
  },
  {
    id: "asteroids",
    parentId: "echinoderms",
    title: { en: "Sea stars", fr: "Étoiles de mer" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47668],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/172397639/original.jpeg"],
  },
  {
    id: "barracudas",
    parentId: "fishes",
    title: { en: "Barracudas", fr: "Barracudas" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47264],
    photos: ["https://static.inaturalist.org/photos/64376618/original.jpeg"],
  },
  {
    id: "bivalves",
    parentId: "molluscs",
    title: { en: "Bivalves", fr: "Bivalves" },
    subtitle: { en: "Clams, oysters, mussels", fr: "Palourdes, huîtres, moules" },
    showSpecies: true,
    includesTaxa: [47584],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/90327867/original.jpeg"],
  },
  {
    id: "black-corals",
    parentId: "cnidarians",
    title: { en: "Black corals", fr: "Coraux noirs" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [121454],
    photos: ["https://static.inaturalist.org/photos/30232137/original.jpg"],
  },
  {
    id: "blennies",
    parentId: "fishes",
    title: { en: "Blennies", fr: "Blennies" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49390],
    photos: ["https://static.inaturalist.org/photos/48993385/original.jpg"],
  },
  {
    id: "boxfishes",
    parentId: "fishes",
    title: { en: "Boxfishes", fr: "Poissons-Coffre" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47529],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/14452691/original.jpg"],
  },
  {
    id: "brachyura",
    parentId: "crustaceans",
    title: { en: "Crabs", fr: "Crabes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [121639],
    photos: ["https://static.inaturalist.org/photos/31056797/original.jpg"],
  },
  {
    id: "bryozoans",
    parentId: "fauna",
    title: { en: "Bryozoans", fr: "Bryozoaires" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [68104],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/2928542/original.JPG",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/665046/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/922198/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/7033627/original.jpg",
    ],
  },
  {
    id: "butterflyfishes",
    parentId: "fishes",
    title: { en: "Butterflyfishes", fr: "Poissons-Papillons" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47318],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/31567731/original.jpeg"],
  },
  {
    id: "calcarea",
    parentId: "sponges",
    title: { en: "Calcarea sponges", fr: "Éponges calcaires" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [60583],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/1039050/original.jpg"],
  },
  {
    id: "cardinalfishes",
    parentId: "fishes",
    title: { en: "Cardinalfishes", fr: "Apogons" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [85594],
    photos: ["https://static.inaturalist.org/photos/38022309/original.jpg"],
  },
  {
    id: "caridea",
    parentId: "crustaceans",
    title: { en: "Shrimps", fr: "Crevettes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [342912],
    photos: ["https://static.inaturalist.org/photos/30395918/original.jpg"],
  },
  {
    id: "cephalopods",
    parentId: "molluscs",
    title: { en: "Cephalopods", fr: "Céphalopodes" },
    subtitle: { en: "Octopus, cuttlefish, squids", fr: "Pieuvres, sèches, calamars" },
    showSpecies: true,
    includesTaxa: [47459],
    photos: ["https://static.inaturalist.org/photos/138354075/original.jpg"],
  },
  {
    id: "chitons",
    parentId: "molluscs",
    title: { en: "Chitons", fr: "Chitons" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47429],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/468853/original.jpg"],
  },
  {
    id: "chlorophyta",
    parentId: "flora",
    title: { en: "Chlorophyta", fr: "Chlorophycées" },
    subtitle: { en: "Green algae", fr: "Algues vertes" },
    showSpecies: true,
    includesTaxa: [50863],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/121415/original.jpg",
      "https://static.inaturalist.org/photos/51179958/original.jpg",
      "https://static.inaturalist.org/photos/46831782/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/27994722/original.jpeg",
    ],
  },
  {
    id: "cnidarians",
    parentId: "fauna",
    title: { en: "Cnidarians", fr: "Cnidaires" },
    subtitle: { en: "Corals, anemones, jellyfish", fr: "Coraux, anémones, méduses" },
    showSpecies: false,
    includesTaxa: [47534],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/91809267/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/60993449/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/13819535/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/78276765/original.jpg",
    ],
  },
  {
    id: "codfishes",
    parentId: "fishes",
    title: { en: "Codfishes", fr: "Morues, aiglefins et merlans" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [63742],
    photos: ["https://static.inaturalist.org/photos/59056282/original.jpeg"],
  },
  {
    id: "crinoidea",
    parentId: "echinoderms",
    title: { en: "Sea lilies", fr: "Comatules" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [51245],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/165312277/original.jpg"],
  },
  {
    id: "crustaceans",
    parentId: "fauna",
    title: { en: "Crustaceans", fr: "Crustacés" },
    subtitle: { en: "Crabs, shrimps, lobsters", fr: "Crabes, crevettes, homards" },
    showSpecies: false,
    includesTaxa: [85493],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/70180984/original.jpg",
      "https://static.inaturalist.org/photos/31056797/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/6276827/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/17002812/original.jpeg",
    ],
  },
  {
    id: "ctenophores",
    parentId: "fauna",
    title: { en: "Ctenophores", fr: "Ctenophores" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [51508],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/17541634/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/99276625/original.jpg",
    ],
  },
  {
    id: "damselfishes-clownfishes",
    parentId: "fishes",
    title: { en: "Damselfishes and Clownfishes", fr: "Demoiselles et Poissons-Clowns" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [48313],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/22203756/original.jpeg"],
  },
  {
    id: "demosponges",
    parentId: "sponges",
    title: { en: "Demosponges and homoscleromorphs", fr: "Démosponges et homoscléromorphes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [57736, 152111],
    photos: ["https://static.inaturalist.org/photos/49137209/original.jpg"],
  },
  {
    id: "echinoderms",
    parentId: "fauna",
    title: { en: "Echinoderms", fr: "Echinodermes" },
    subtitle: { en: "Sea stars, sea urchins, sea cucumbers", fr: "Étoiles de mer, oursins, concombre des mers" },
    showSpecies: false,
    includesTaxa: [47549],
    photos: [
      "https://static.inaturalist.org/photos/99800998/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/172397639/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/1012882/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/184811284/original.jpg",
    ],
  },
  {
    id: "echinoidea",
    parentId: "echinoderms",
    title: { en: "Sea urchins", fr: "Oursins" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47548],
    photos: ["https://static.inaturalist.org/photos/54970089/original.jpeg"],
  },
  {
    id: "emperors",
    parentId: "fishes",
    title: { en: "Emperors", fr: "Empereurs" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [55207],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/42083590/original.jpeg"],
  },
  {
    id: "epinephelidae",
    parentId: "fishes",
    title: { en: "Groupers", fr: "Mérous" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1363728],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/429735/original.jpg"],
  },
  {
    id: "fauna",
    parentId: null,
    title: { en: "Fauna", fr: "Faune" },
    subtitle: {},
    showSpecies: false,
    includesTaxa: [1],
    photos: [],
  },
  {
    id: "filefishes",
    parentId: "fishes",
    title: { en: "Filefishes", fr: "Monacanthes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47176],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/8033213/original.jpg"],
  },
  {
    id: "fishes",
    parentId: "fauna",
    title: { en: "Actinopterygii", fr: "Actinoptérygiens" },
    subtitle: { en: "Ray-finned fishes", fr: "Poissons à nageoires rayonnées" },
    showSpecies: false,
    includesTaxa: [47178],
    photos: [
      "https://static.inaturalist.org/photos/59568714/original.jpg",
      "https://static.inaturalist.org/photos/27540586/original.jpg",
      "https://static.inaturalist.org/photos/25021300/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/60018095/original.jpg",
    ],
  },
  {
    id: "flat-worms",
    parentId: "fauna",
    title: { en: "Platyhelminthes", fr: "Plathelminthes" },
    subtitle: { en: "Flat worms", fr: "Vers plats" },
    showSpecies: true,
    includesTaxa: [52319],
    photos: [
      "https://static.inaturalist.org/photos/30267559/original.jpg",
      "https://static.inaturalist.org/photos/3416894/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/2566027/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/4331401/original.jpg",
    ],
  },
  {
    id: "flora",
    parentId: null,
    title: { en: "Flora", fr: "Flore" },
    subtitle: {},
    showSpecies: false,
    includesTaxa: [47126, 48222],
    photos: [],
  },
  {
    id: "gastropods",
    parentId: "molluscs",
    title: { en: "Gastropods", fr: "Gastéropodes" },
    subtitle: { en: "Snails, slugs, whelks", fr: "Escargots, limaces, bigorneaux" },
    showSpecies: true,
    includesTaxa: [47114],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/6144962/original.jpg"],
  },
  {
    id: "ghost-pipefishes",
    parentId: "fishes",
    title: { en: "Ghost pipefishes", fr: "Poissons-Fantômes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [86072],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/66458743/original.jpg"],
  },
  {
    id: "goatfishes",
    parentId: "fishes",
    title: { en: "Goatfishes or Red mullets", fr: "Surmulets ou Rougets" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [118620],
    photos: ["https://static.inaturalist.org/photos/27542271/original.jpg"],
  },
  {
    id: "gobies",
    parentId: "fishes",
    title: { en: "Gobies", fr: "Gobies" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47308],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/78444930/original.jpeg"],
  },
  {
    id: "grunts",
    parentId: "fishes",
    title: { en: "Grunts", fr: "Haemulidae" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49263],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/174462898/original.jpeg"],
  },
  {
    id: "hard-corals",
    parentId: "cnidarians",
    title: { en: "Hard corals", fr: "Coraux durs / Batisseurs de récifs" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47532, 152818],
    photos: ["https://static.inaturalist.org/photos/55717033/original.jpeg"],
  },
  {
    id: "herrings",
    parentId: "fishes",
    title: { en: "Herrings, shads, sardines, hilsa, and menhadens", fr: "Harengs, aloses, sardines et menhadens" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49236, 1416131],
    photos: ["https://static.inaturalist.org/photos/52936935/original.jpg"],
  },
  {
    id: "hexactinellida",
    parentId: "sponges",
    title: { en: "Hexactinellida sponges", fr: "Éponges hexactinellides" },
    subtitle: { en: "Glass sponges", fr: "Éponges de verre" },
    showSpecies: true,
    includesTaxa: [],
    photos: [],
  },
  {
    id: "hexanauplia",
    parentId: "crustaceans",
    title: { en: "Barnacles", fr: "Balanes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1091452],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/17002812/original.jpeg"],
  },
  {
    id: "holothuroidea",
    parentId: "echinoderms",
    title: { en: "Sea cucumbers", fr: "Concombres de mer" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47720],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/23217983/original.jpeg"],
  },
  {
    id: "hydrozoa",
    parentId: "cnidarians",
    title: { en: "Hydrozoans", fr: "Hydrozoaires" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [48921],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/226672798/original.jpg"],
  },
  {
    id: "jellyfishes",
    parentId: "cnidarians",
    title: { en: "Jellyfishes", fr: "Méduses" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [48332, 68095, 51019],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/91809267/original.jpg"],
  },
  {
    id: "labridae",
    parentId: "fishes",
    title: { en: "Wrasses", fr: "Labres" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49284],
    photos: ["https://static.inaturalist.org/photos/27540586/original.jpg"],
  },
  {
    id: "lizardfishes",
    parentId: "fishes",
    title: { en: "Lizardfishes", fr: "Poissons-Lézard" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49410],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/9320743/original.png"],
  },
  {
    id: "mackerels-tunas-bonitos",
    parentId: "fishes",
    title: { en: "Mackerels, tunas and bonitos", fr: "Maquereaux, thons et bonites" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47266],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/166749808/original.jpeg"],
  },
  {
    id: "molluscs",
    parentId: "fauna",
    title: { en: "Molluscs", fr: "Mollusques" },
    subtitle: { en: "Octopus, slugs, shells", fr: "Pieuvres, limaces, coquillages" },
    showSpecies: false,
    includesTaxa: [47115],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/54629807/original.jpeg",
      "https://static.inaturalist.org/photos/138354075/original.jpg",
      "https://static.inaturalist.org/photos/2667318/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/468853/original.jpg",
    ],
  },
  {
    id: "mullets",
    parentId: "fishes",
    title: { en: "Mullets", fr: "Mulet" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [54661],
    photos: ["https://static.inaturalist.org/photos/59568714/original.jpg"],
  },
  {
    id: "needlefishes",
    parentId: "fishes",
    title: { en: "Needlefishes", fr: "Aiguillettes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [52461],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/207417850/original.jpeg"],
  },
  {
    id: "ophiuroidea",
    parentId: "echinoderms",
    title: { en: "Brittle stars", fr: "Ophiures" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [48836],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/14735833/original.jpeg"],
  },
  {
    id: "phaeophyceae",
    parentId: "flora",
    title: { en: "Phaeophyceae", fr: "Phaeophycées" },
    subtitle: { en: "Brown algae", fr: "Algues brunes" },
    showSpecies: true,
    includesTaxa: [48220],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/121411/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/666724/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/956769/original.jpg",
      "https://static.inaturalist.org/photos/17250150/original.jpeg",
    ],
  },
  {
    id: "pleuronectoidei",
    parentId: "fishes",
    title: { en: "Flatfishes", fr: "Poissons plat" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1303751],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/161931149/original.jpeg"],
  },
  {
    id: "porcupinefishes",
    parentId: "fishes",
    title: { en: "Porcupinefishes", fr: "Poisson Porc-Épic" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49270],
    photos: ["https://static.inaturalist.org/photos/13565772/original.jpeg"],
  },
  {
    id: "pufferfishes",
    parentId: "fishes",
    title: { en: "Pufferfishes", fr: "Poissons-Globes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49266],
    photos: ["https://static.inaturalist.org/photos/13138055/original.jpg"],
  },
  {
    id: "rabbitfishes",
    parentId: "fishes",
    title: { en: "Rabbitfishes", fr: "Poissons-lapins" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [84096],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/172083046/original.jpeg"],
  },
  {
    id: "rays",
    parentId: "sharks-rays",
    title: { en: "Rays", fr: "Raies" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [448201],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/128652319/original.jpeg"],
  },
  {
    id: "reptiles",
    parentId: "fauna",
    title: { en: "Reptiles", fr: "Reptiles" },
    subtitle: { fr: "Tortues de mer" },
    showSpecies: true,
    includesTaxa: [26036],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/155639810/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/248337518/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/172235708/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/175401034/original.jpg",
    ],
  },
  {
    id: "rhodophyta",
    parentId: "flora",
    title: { en: "Rhodophyta", fr: "Rhodophycées" },
    subtitle: { en: "Red algae", fr: "Algues rouges" },
    showSpecies: true,
    includesTaxa: [57774],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/1774938/original.JPG",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/248890633/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/58703938/original.jpg",
      "https://static.inaturalist.org/photos/109190400/original.jpg",
    ],
  },
  {
    id: "sandlances",
    parentId: "fishes",
    title: { en: "Sandlances", fr: "Lançons" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [85574],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/149857224/original.jpeg"],
  },
  {
    id: "scarini",
    parentId: "fishes",
    title: { en: "Parrotfishes", fr: "Poissons perroquets" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1455139],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/230907136/original.jpeg"],
  },
  {
    id: "sciaenidae",
    parentId: "fishes",
    title: { en: "Drums", fr: "Corbs" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49172],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/55438306/original.jpg"],
  },
  {
    id: "scorpaenidae",
    parentId: "fishes",
    title: { en: "Scorpionfishes", fr: "Rascasses" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47285],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/4643920/original.jpg"],
  },
  {
    id: "scorpionfishes",
    parentId: "fishes",
    title: { en: "Scorpionfishes", fr: "Poissons-Pierre" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [64494],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/240296548/original.jpg"],
  },
  {
    id: "seabasses",
    parentId: "fishes",
    title: { en: "Seabasses", fr: "Loup de mer" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1359791],
    photos: ["https://static.inaturalist.org/photos/12505596/original.jpg"],
  },
  {
    id: "seahorses-pipefishes",
    parentId: "fishes",
    title: { en: "Seahorses and pipefishes", fr: "Hippocampes et Syngnathes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49106],
    photos: ["https://static.inaturalist.org/photos/49705000/original.jpg"],
  },
  {
    id: "serranidae",
    parentId: "fishes",
    title: { en: "Comber", fr: "Sérans" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47765],
    photos: ["https://static.inaturalist.org/photos/27542282/original.jpg"],
  },
  {
    id: "sharks",
    parentId: "sharks-rays",
    title: { en: "Sharks", fr: "Requins" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [551307],
    photos: ["https://static.inaturalist.org/photos/87114970/original.jpg"],
  },
  {
    id: "sharks-rays",
    parentId: "fauna",
    title: { en: "Cartilaginous fishes", fr: "Poissons cartilagineux" },
    subtitle: { en: "Sharks and rays", fr: "Requins et raies" },
    showSpecies: false,
    includesTaxa: [505362],
    photos: [
      "https://static.inaturalist.org/photos/87114970/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/10571121/original.jpg",
      "https://static.inaturalist.org/photos/155822398/original.jpg",
      "https://static.inaturalist.org/photos/71600717/original.jpg",
    ],
  },
  {
    id: "snappers",
    parentId: "fishes",
    title: { en: "Snappers", fr: "Vivaneaux" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47295],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/12126082/original.jpg"],
  },
  {
    id: "soft-corals",
    parentId: "cnidarians",
    title: { en: "Soft corals", fr: "Coraux mous" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [1435134, 1435135],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/79085844/original.jpg"],
  },
  {
    id: "soldierfishes-squirrelfishes",
    parentId: "fishes",
    title: { en: "Soldierfishes and Squirrelfishes", fr: "Poissons-soldats et Poissons écureuils" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49628],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/3680239/original.jpg"],
  },
  {
    id: "spadefishes",
    parentId: "fishes",
    title: { en: "Spadefishes", fr: "Ephippidae" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49317],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/35639085/original.jpg"],
  },
  {
    id: "sparidae",
    parentId: "fishes",
    title: { en: "Porgies", fr: "Sars" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49238],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/156153979/original.jpg"],
  },
  {
    id: "sponges",
    parentId: "fauna",
    title: { en: "Porifera", fr: "Porifères" },
    subtitle: { en: "Sponges", fr: "Éponges" },
    showSpecies: false,
    includesTaxa: [48824],
    photos: [
      "https://inaturalist-open-data.s3.amazonaws.com/photos/144740700/original.jpg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/178687595/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/37553070/original.jpeg",
      "https://inaturalist-open-data.s3.amazonaws.com/photos/154760564/original.jpeg",
    ],
  },
  {
    id: "stargazers",
    parentId: "fishes",
    title: { en: "stargazers", fr: "Uranoscopes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [86126],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/175995531/original.jpg"],
  },
  {
    id: "surgeonfishes",
    parentId: "fishes",
    title: { en: "Surgeonfishes", fr: "Poissons-chirurgiens et Poissons-Licornes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47619],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/11763004/original.jpg"],
  },
  {
    id: "temperate-basses",
    parentId: "fishes",
    title: { en: "Temperate basses", fr: "Bars" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [51393],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/198872814/original.jpeg"],
  },
  {
    id: "trachinidae",
    parentId: "fishes",
    title: { en: "Weevers", fr: "Vives" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [86107],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/2592961/original.jpg"],
  },
  {
    id: "trevallies",
    parentId: "fishes",
    title: { en: "Trevallies and related", fr: "Carangues et apparentés" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [47232],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/43925888/original.jpeg"],
  },
  {
    id: "triggerfishes",
    parentId: "fishes",
    title: { en: "Triggerfishes", fr: "Balistes" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [49612],
    photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/243368980/original.jpg"],
  },
  {
    id: "triglidae",
    parentId: "fishes",
    title: { en: "Sea robins", fr: "Grondins" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [48563],
    photos: ["https://static.inaturalist.org/photos/3426378/original.jpg"],
  },
  {
    id: "zoanthids",
    parentId: "cnidarians",
    title: { en: "Zoanthids", fr: "Zoantharias" },
    subtitle: {},
    showSpecies: true,
    includesTaxa: [51198],
    photos: ["https://static.inaturalist.org/photos/93328271/original.jpg"],
  },
]
