export const groups = [
  {
    parent_id: null,
    includes: [1],
    id: "fauna",
    title: { en: "Fauna", fr: "Faune" },
    children: [
      {
        parent_id: "fauna",
        subtitle: { en: "Ray-finned fishes", fr: "Poissons à nageoires rayonnées" },
        includes: [47178],
        id: "actinopterygii",
        title: { en: "Actinopterygii", fr: "Actinoptérygiens" },
        photos: [
          "https://static.inaturalist.org/photos/59568714/original.jpg",
          "https://static.inaturalist.org/photos/27540586/original.jpg",
          "https://static.inaturalist.org/photos/25021300/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/60018095/original.jpg",
        ],
        children: [
          {
            parent_id: "fishes",
            includes: [47237],
            id: "angelfishes",
            title: { en: "Angelfishes", fr: "Poissons-Anges" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/231970034/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47314],
            id: "eels,-congers,-morays",
            title: { en: "Eels, congers, morays", fr: "Anguilles, congres, murènes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/60018095/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47264],
            id: "barracudas",
            title: { en: "Barracudas", fr: "Barracudas" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/64376618/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49390],
            id: "blennies",
            title: { en: "Blennies", fr: "Blennies" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/48993385/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47529],
            id: "boxfishes",
            title: { en: "Boxfishes", fr: "Poissons-Coffre" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/14452691/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47318],
            id: "butterflyfishes",
            title: { en: "Butterflyfishes", fr: "Poissons-Papillons" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/31567731/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [85594],
            id: "cardinalfishes",
            title: { en: "Cardinalfishes", fr: "Apogons" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/38022309/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [63742],
            id: "codfishes",
            title: { en: "Codfishes", fr: "Morues, aiglefins et merlans" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/59056282/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [48313],
            id: "damselfishes-and-clownfishes",
            title: { en: "Damselfishes and Clownfishes", fr: "Demoiselles et Poissons-Clowns" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/22203756/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [55207],
            id: "emperors",
            title: { en: "Emperors", fr: "Empereurs" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/42083590/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [1363728],
            id: "groupers",
            title: { en: "Groupers", fr: "Mérous" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/429735/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47176],
            id: "filefishes",
            title: { en: "Filefishes", fr: "Monacanthes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/8033213/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [86072],
            id: "ghost-pipefishes",
            title: { en: "Ghost pipefishes", fr: "Poissons-Fantômes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/66458743/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [118620],
            id: "goatfishes-or-red-mullets",
            title: { en: "Goatfishes or Red mullets", fr: "Surmulets ou Rougets" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/27542271/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47308],
            id: "gobies",
            title: { en: "Gobies", fr: "Gobies" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/78444930/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49263],
            id: "grunts",
            title: { en: "Grunts", fr: "Haemulidae" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/174462898/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49236, 1416131],
            id: "herrings,-shads,-sardines,-hilsa,-and-menhadens",
            title: {
              en: "Herrings, shads, sardines, hilsa, and menhadens",
              fr: "Harengs, aloses, sardines et menhadens",
            },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/52936935/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49284],
            id: "wrasses",
            title: { en: "Wrasses", fr: "Labres" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/27540586/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49410],
            id: "lizardfishes",
            title: { en: "Lizardfishes", fr: "Poissons-Lézard" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/9320743/original.png"],
          },
          {
            parent_id: "fishes",
            includes: [47266],
            id: "mackerels,-tunas-and-bonitos",
            title: { en: "Mackerels, tunas and bonitos", fr: "Maquereaux, thons et bonites" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/166749808/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [54661],
            id: "mullets",
            title: { en: "Mullets", fr: "Mulet" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/59568714/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [52461],
            id: "needlefishes",
            title: { en: "Needlefishes", fr: "Aiguillettes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/207417850/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [1303751],
            id: "flatfishes",
            title: { en: "Flatfishes", fr: "Poissons plat" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/161931149/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49270],
            id: "porcupinefishes",
            title: { en: "Porcupinefishes", fr: "Poisson Porc-Épic" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/13565772/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49266],
            id: "pufferfishes",
            title: { en: "Pufferfishes", fr: "Poissons-Globes" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/13138055/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [84096],
            id: "rabbitfishes",
            title: { en: "Rabbitfishes", fr: "Poissons-lapins" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/172083046/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [85574],
            id: "sandlances",
            title: { en: "Sandlances", fr: "Lançons" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/149857224/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [1455139],
            id: "parrotfishes",
            title: { en: "Parrotfishes", fr: "Poissons perroquets" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/230907136/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49172],
            id: "drums",
            title: { en: "Drums", fr: "Corbs" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/55438306/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47285],
            id: "scorpionfishes",
            title: { en: "Scorpionfishes", fr: "Rascasses" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/4643920/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [64494],
            id: "scorpionfishes",
            title: { en: "Scorpionfishes", fr: "Poissons-Pierre" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/240296548/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [1359791],
            id: "seabasses",
            title: { en: "Seabasses", fr: "Loup de mer" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/12505596/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49106],
            id: "seahorses-and-pipefishes",
            title: { en: "Seahorses and pipefishes", fr: "Hippocampes et Syngnathes" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/49705000/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47765],
            id: "comber",
            title: { en: "Comber", fr: "Sérans" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/27542282/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47295],
            id: "snappers",
            title: { en: "Snappers", fr: "Vivaneaux" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/12126082/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49628],
            id: "soldierfishes-and-squirrelfishes",
            title: { en: "Soldierfishes and Squirrelfishes", fr: "Poissons-soldats et Poissons écureuils" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/3680239/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49317],
            id: "spadefishes",
            title: { en: "Spadefishes", fr: "Ephippidae" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/35639085/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [49238],
            id: "porgies",
            title: { en: "Porgies", fr: "Sars" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/156153979/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [86126],
            id: "stargazers",
            title: { en: "stargazers", fr: "Uranoscopes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/175995531/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47619],
            id: "surgeonfishes",
            title: { en: "Surgeonfishes", fr: "Poissons-chirurgiens et Poissons-Licornes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/11763004/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [51393],
            id: "temperate-basses",
            title: { en: "Temperate basses", fr: "Bars" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/198872814/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [86107],
            id: "weevers",
            title: { en: "Weevers", fr: "Vives" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/2592961/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [47232],
            id: "trevallies-and-related",
            title: { en: "Trevallies and related", fr: "Carangues et apparentés" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/43925888/original.jpeg"],
          },
          {
            parent_id: "fishes",
            includes: [49612],
            id: "triggerfishes",
            title: { en: "Triggerfishes", fr: "Balistes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/243368980/original.jpg"],
          },
          {
            parent_id: "fishes",
            includes: [48563],
            id: "sea-robins",
            title: { en: "Sea robins", fr: "Grondins" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/3426378/original.jpg"],
          },
        ],
      },
      {
        parent_id: "fauna",
        subtitle: { en: "Flat worms", fr: "Vers plats" },
        includes: [52319],
        id: "platyhelminthes",
        title: { en: "Platyhelminthes", fr: "Plathelminthes" },
        show_species: true,
        photos: [
          "https://static.inaturalist.org/photos/30267559/original.jpg",
          "https://static.inaturalist.org/photos/3416894/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/2566027/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/4331401/original.jpg",
        ],
      },
      {
        parent_id: "fauna",
        subtitle: { en: "Octopus, slugs, shells", fr: "Pieuvres, limaces, coquillages" },
        includes: [47115],
        id: "molluscs",
        title: { en: "Molluscs", fr: "Mollusques" },
        photos: [
          "https://inaturalist-open-data.s3.amazonaws.com/photos/54629807/original.jpeg",
          "https://static.inaturalist.org/photos/138354075/original.jpg",
          "https://static.inaturalist.org/photos/2667318/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/468853/original.jpg",
        ],
        children: [
          {
            parent_id: "molluscs",
            subtitle: { en: "Clams, oysters, mussels", fr: "Palourdes, huîtres, moules" },
            includes: [47584],
            id: "bivalves",
            title: { en: "Bivalves", fr: "Bivalves" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/90327867/original.jpeg"],
          },
          {
            parent_id: "molluscs",
            subtitle: { en: "Octopus, cuttlefish, squids", fr: "Pieuvres, sèches, calamars" },
            includes: [47459],
            id: "cephalopods",
            title: { en: "Cephalopods", fr: "Céphalopodes" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/138354075/original.jpg"],
          },
          {
            parent_id: "molluscs",
            includes: [47429],
            id: "chitons",
            title: { en: "Chitons", fr: "Chitons" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/468853/original.jpg"],
          },
          {
            parent_id: "molluscs",
            subtitle: { en: "Snails, slugs, whelks", fr: "Escargots, limaces, bigorneaux" },
            includes: [47114],
            id: "gastropods",
            title: { en: "Gastropods", fr: "Gastéropodes" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/6144962/original.jpg"],
          },
        ],
      },
      {
        parent_id: "fauna",
        subtitle: { fr: "Tortues de mer" },
        includes: [26036],
        id: "reptiles",
        title: { en: "Reptiles", fr: "Reptiles" },
        show_species: true,
        photos: [
          "https://inaturalist-open-data.s3.amazonaws.com/photos/155639810/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/248337518/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/172235708/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/175401034/original.jpg",
        ],
      },
      {
        parent_id: "fauna",
        subtitle: { en: "Sharks and rays", fr: "Requins et raies" },
        includes: [505362],
        id: "cartilaginous-fishes",
        title: { en: "Cartilaginous fishes", fr: "Poissons cartilagineux" },
        photos: [
          "https://static.inaturalist.org/photos/87114970/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/10571121/original.jpg",
          "https://static.inaturalist.org/photos/155822398/original.jpg",
          "https://static.inaturalist.org/photos/71600717/original.jpg",
        ],
        children: [
          {
            parent_id: "sharks-rays",
            includes: [448201],
            id: "rays",
            title: { en: "Rays", fr: "Raies" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/128652319/original.jpeg"],
          },
          {
            parent_id: "sharks-rays",
            includes: [551307],
            id: "sharks",
            title: { en: "Sharks", fr: "Requins" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/87114970/original.jpg"],
          },
        ],
      },
      {
        parent_id: "fauna",
        subtitle: { en: "Sponges", fr: "Éponges" },
        includes: [48824],
        id: "porifera",
        title: { en: "Porifera", fr: "Porifères" },
        photos: [
          "https://inaturalist-open-data.s3.amazonaws.com/photos/144740700/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/178687595/original.jpeg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/37553070/original.jpeg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/154760564/original.jpeg",
        ],
        children: [
          {
            parent_id: "sponges",
            includes: [60583],
            id: "calcarea-sponges",
            title: { en: "Calcarea sponges", fr: "Éponges calcaires" },
            show_species: true,
            photos: ["https://inaturalist-open-data.s3.amazonaws.com/photos/1039050/original.jpg"],
          },
          {
            parent_id: "sponges",
            includes: [57736, 152111],
            id: "demosponges-and-homoscleromorphs",
            title: { en: "Demosponges and homoscleromorphs", fr: "Démosponges et homoscléromorphes" },
            show_species: true,
            photos: ["https://static.inaturalist.org/photos/49137209/original.jpg"],
          },
          {
            parent_id: "sponges",
            subtitle: { en: "Glass sponges", fr: "Éponges de verre" },
            includes: [152110],
            id: "hexactinellida-sponges",
            title: { en: "Hexactinellida sponges", fr: "Éponges hexactinellides" },
            show_species: true,
            photos: [],
          },
        ],
      },
    ],
  },
  {
    parent_id: null,
    includes: [47126, 48222],
    id: "flora",
    title: { en: "Flora", fr: "Flore" },
    children: [
      {
        parent_id: "flora",
        subtitle: { en: "Brown algae", fr: "Algues brunes" },
        includes: [48220],
        id: "phaeophyceae",
        title: { en: "Phaeophyceae", fr: "Phaeophycées" },
        show_species: true,
        photos: [
          "https://inaturalist-open-data.s3.amazonaws.com/photos/121411/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/666724/original.jpg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/956769/original.jpg",
          "https://static.inaturalist.org/photos/17250150/original.jpeg",
        ],
      },
      {
        parent_id: "flora",
        subtitle: { en: "Red algae", fr: "Algues rouges" },
        includes: [57774],
        id: "rhodophyta",
        title: { en: "Rhodophyta", fr: "Rhodophycées" },
        show_species: true,
        photos: [
          "https://inaturalist-open-data.s3.amazonaws.com/photos/1774938/original.JPG",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/248890633/original.jpeg",
          "https://inaturalist-open-data.s3.amazonaws.com/photos/58703938/original.jpg",
          "https://static.inaturalist.org/photos/109190400/original.jpg",
        ],
      },
    ],
  },
]
