export interface IFishbaseSpecies {
  SpecCode: number
  Genus: string
  Species: string
  SpeciesRefNo: number
  Author: string
  FBname: string
  PicPreferredName: string
  PicPreferredNameM: string
  PicPreferredNameF: string
  PicPreferredNameJ: any
  FamCode: number
  Subfamily: string
  GenCode: number
  SubGenCode: any
  BodyShapeI: string
  Source: string
  AuthorRef: any
  Remark: any
  TaxIssue: number
  Fresh: number
  Brack: number
  Saltwater: number
  DemersPelag: string
  Amphibious: any
  AmphibiousRef: any
  AnaCat: any
  MigratRef: any
  DepthRangeShallow: number
  DepthRangeDeep: number
  DepthRangeRef: number
  DepthRangeComShallow: number
  DepthRangeComDeep: number
  DepthComRef: number
  LongevityWild: number
  LongevityWildRef: number
  LongevityCaptive: any
  LongevityCapRef: any
  Vulnerability: number
  Length: number
  LTypeMaxM: string
  LengthFemale: any
  LTypeMaxF: any
  MaxLengthRef: number
  CommonLength: number
  LTypeComM: string
  CommonLengthF: any
  LTypeComF: any
  CommonLengthRef: number
  Weight: any
  WeightFemale: any
  MaxWeightRef: any
  Pic: string
  PictureFemale: any
  LarvaPic: string
  EggPic: any
  ImportanceRef: number
  Importance: string
  PriceCateg: string
  PriceReliability: string
  Remarks7: any
  LandingStatistics: any
  Landings: any
  MainCatchingMethod: string
  II: string
  MSeines: number
  MGillnets: number
  MCastnets: number
  MTraps: number
  MSpears: number
  MTrawls: number
  MDredges: number
  MLiftnets: number
  MHooksLines: number
  MOther: number
  UsedforAquaculture: string
  LifeCycle: string
  AquacultureRef: any
  UsedasBait: string
  BaitRef: any
  Aquarium: string
  AquariumFishII: string
  AquariumRef: number
  GameFish: number
  GameRef: number
  Dangerous: string
  DangerousRef: any
  Electrogenic: string
  ElectroRef: any
  Complete: any
  GoogleImage: number
  Comments: string
  Profile: any
  PD50: number
  Emblematic: number
  Entered: number
  DateEntered: string
  Modified: number
  DateModified: string
  Expert: number
  DateChecked: string
  TS: any
}
